CREATE TABLE UserHasRole (
   id INT NOT NULL  AUTO_INCREMENT,
   user_id INT(11) NOT NULL  ,
   role_name VARCHAR(50) NOT NULL DEFAULT 'admin' ,
   createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
   updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
   active BOOLEAN NOT NULL  ,
   PRIMARY KEY (id),
   FOREIGN KEY (user_id) REFERENCES AdminUsers(id)
);